/**
 * config.js is gitignored (real credentials are generated at deploy time —
 * see config.example.js) and genuinely absent in CI/dev containers. Some
 * modules (auth.js) import named exports from it directly, and node:test's
 * mock.module() can only intercept a specifier that resolves to a real file
 * on disk — it does not create modules out of thin air. So tests that need
 * to mock config.js must first guarantee *a* file exists at that path; its
 * content is irrelevant since mock.module() fully replaces the exports.
 *
 * ensureTestConfig() never overwrites a real local config.js a contributor
 * may already have — it only creates one if missing, and only removes the
 * one it created.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname   = path.dirname(fileURLToPath(import.meta.url));
const CONFIG_PATH = path.join(__dirname, "..", "..", "config.js");

const PLACEHOLDER =
  "// Placeholder auto-generated by tests/mocks/configFixture.js — safe to delete.\n" +
  "export const SUPABASE_URL = \"https://test.invalid\";\n" +
  "export const SUPABASE_ANON_KEY = \"test-anon-key\";\n" +
  "export const APP_URL = \"http://localhost:8080\";\n" +
  "export const VAPID_PUBLIC_KEY = \"\";\n";

/** Returns a restore() function — call it after the test run completes. */
export function ensureTestConfig() {
  if (fs.existsSync(CONFIG_PATH)) return () => {};
  fs.writeFileSync(CONFIG_PATH, PLACEHOLDER);
  return () => {
    try { fs.unlinkSync(CONFIG_PATH); } catch { /* already gone */ }
  };
}
