/**
 * config.js is gitignored (real credentials are generated at deploy time —
 * see config.example.js) and genuinely absent in CI/dev containers. Some
 * modules (auth.js) import named exports from it directly, and node:test's
 * mock.module() can only intercept a specifier that resolves to a real file
 * on disk — it does not create modules out of thin air. So tests that need
 * to mock config.js must first guarantee *a* file exists at that path; its
 * content is irrelevant since mock.module() fully replaces the exports.
 *
 * ensureTestConfig() never overwrites a real local config.js a contributor
 * may already have — it only creates one if missing. It never deletes it
 * either: `npm test` runs every test file that calls this in parallel
 * (auth.test.js, scriptAppInit.test.js, settingsModal.test.js), each in its
 * own process but sharing this same on-disk path, so one file's cleanup
 * could delete the placeholder while another was still mid-run (intermittent
 * ERR_MODULE_NOT_FOUND). The placeholder is gitignored and self-labeled
 * "safe to delete", so leaving it behind is harmless.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname   = path.dirname(fileURLToPath(import.meta.url));
const CONFIG_PATH = path.join(__dirname, "..", "..", "config.js");

const PLACEHOLDER =
  "// Placeholder auto-generated by tests/mocks/configFixture.js — safe to delete.\n" +
  "export const SUPABASE_URL = \"https://test.invalid\";\n" +
  "export const SUPABASE_ANON_KEY = \"test-anon-key\";\n" +
  "export const APP_URL = \"http://localhost:8080\";\n" +
  "export const VAPID_PUBLIC_KEY = \"\";\n";

/**
 * Returns a restore() function for symmetry with the previous cleanup-based
 * API (existing before/after hooks keep working unchanged) — it is now a
 * no-op, kept on purpose (see comment above).
 */
export function ensureTestConfig() {
  if (!fs.existsSync(CONFIG_PATH)) fs.writeFileSync(CONFIG_PATH, PLACEHOLDER);
  return () => {};
}
